### ISSUE TITLE
Add progress message

### ISSUE THREAD

**Issue by CodeLoos** [NagelsThomas/pendulum-experience#7]
Would it be possible to change the loading message from "creating visualizations" to "performing dynamic calculations" or something in that direction?

![Pendulum](https://github.com/viktor-platform/pendulum-experience/assets/137996190/fd3ae109-8b2b-42e4-ac95-ce268eb43c35)

**Comment by LuukBoot** [comment]
I was trying to get more updates about the GIF, because this can take a while. However saving the GIF in a NamedTemporaryFIle takes the most amount of time and I see no way to add a progress message.
